"""Auto-generated audit report — summary stats per processed CSV.

Reads every ``data/processed/<election>-city-of-boulder-wide.csv``, computes
basic shape / dtype / null / cardinality stats, and writes a Markdown
report to ``data/audit/summary-<YYYYMMDD-HHMMSS>.md`` plus a stable
``data/audit/summary.md`` (the latest report).

Also writes ``docs/variables.md`` + ``docs/variables.csv`` — auto-generated
column profile to complement the hand-maintained
``docs/data-dictionary.md``.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import pandas as pd

from .config import AUDIT_DIR, DOCS_DIR, PROCESSED_DIR, SUMMARY_CSV, ensure_dirs
from .schema import contest_columns, id_columns


def _list_processed() -> list[Path]:
    return sorted(PROCESSED_DIR.glob("*-city-of-boulder-wide.csv"))


def _summarize_one(path: Path) -> dict:
    df = pd.read_csv(path, low_memory=False)
    return {
        "path":         path,
        "n_ballots":    len(df),
        "n_id_cols":    len(id_columns(df)),
        "n_contest_cols": len(contest_columns(df)),
        "memory_mb":    df.memory_usage(index=False, deep=True).sum() / 1e6,
        "null_pct":     float(df.isna().mean().mean() * 100),
    }


def write_audit(verbose: bool = True) -> Path:
    """Write a Markdown audit report. Returns the report path."""
    ensure_dirs()
    files = _list_processed()
    if not files:
        raise SystemExit(
            "no processed CSVs found in data/processed/; "
            "run `python -m scripts.clean` first"
        )

    rows = [_summarize_one(p) for p in files]

    ts = time.strftime("%Y%m%d-%H%M%S")
    out_path = AUDIT_DIR / f"summary-{ts}.md"
    stable_path = AUDIT_DIR / "summary.md"

    lines: list[str] = []
    lines.append(f"# Audit Summary — {ts}")
    lines.append("")
    lines.append(
        "Auto-generated by `python -m scripts.audit`. The hand-maintained "
        "documentation lives in `docs/data-dictionary.md`."
    )
    lines.append("")
    lines.append("## Per-election shape")
    lines.append("")
    lines.append("| Election | n ballots | ID cols | contest cols | mem (MB) | null % |")
    lines.append("| --- | ---: | ---: | ---: | ---: | ---: |")
    for r in rows:
        key = r["path"].name.removesuffix("-city-of-boulder-wide.csv")
        lines.append(
            f"| {key} | {r['n_ballots']:,} | {r['n_id_cols']} | "
            f"{r['n_contest_cols']} | {r['memory_mb']:.1f} | "
            f"{r['null_pct']:.1f} |"
        )
    lines.append("")

    if SUMMARY_CSV.exists():
        lines.append("## Pipeline bookkeeping (`data/processed/_summary.csv`)")
        lines.append("")
        s = pd.read_csv(SUMMARY_CSV).set_index("election_key")
        lines.append(s.to_markdown())
        lines.append("")

    lines.append("## Files in `data/original/`")
    lines.append("")
    from .fetch import load_manifest
    manifest = load_manifest()
    if manifest:
        lines.append("| File | SHA-256 (first 12) | size (MB) | mtime |")
        lines.append("| --- | --- | ---: | --- |")
        for fname, info in sorted(manifest.items()):
            lines.append(
                f"| `{fname}` | `{info['sha256'][:12]}` | "
                f"{info['size']/1e6:.1f} | {info['mtime_iso']} |"
            )
    else:
        lines.append("(manifest.json not yet generated; run `python -m scripts.fetch`)")
    lines.append("")

    text = "\n".join(lines) + "\n"
    out_path.write_text(text)
    stable_path.write_text(text)

    if verbose:
        print(f"  wrote {out_path}")
        print(f"  wrote {stable_path}")

    _write_variables_report(rows, verbose=verbose)
    return out_path


def _write_variables_report(rows: list[dict], verbose: bool) -> None:
    """Per-column profile across every processed CSV.

    Writes ``docs/variables.csv`` (machine-readable) and ``docs/variables.md``.
    """
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    records: list[dict] = []
    for r in rows:
        key = r["path"].name.removesuffix("-city-of-boulder-wide.csv")
        df = pd.read_csv(r["path"], low_memory=False, nrows=5000)
        for col in df.columns:
            kind = "id" if col.startswith("_ID/") else "contest"
            records.append({
                "election_key": key,
                "column":       col,
                "kind":         kind,
                "dtype":        str(df[col].dtype),
                "n_distinct":   int(df[col].nunique(dropna=True)),
                "null_pct":     float(df[col].isna().mean() * 100),
            })
    if not records:
        return
    variables = pd.DataFrame(records)
    variables.to_csv(DOCS_DIR / "variables.csv", index=False)

    lines = [
        "# Variables (auto-generated)\n",
        "Mechanical profile of every column in every processed CSV. "
        "Sampled on the first 5,000 rows per file. The hand-maintained "
        "documentation lives in `docs/data-dictionary.md`.\n",
        "| election_key | column | kind | dtype | n_distinct | null % |",
        "| --- | --- | --- | --- | ---: | ---: |",
    ]
    for rec in records:
        lines.append(
            f"| {rec['election_key']} | `{rec['column']}` | {rec['kind']} | "
            f"{rec['dtype']} | {rec['n_distinct']} | {rec['null_pct']:.1f} |"
        )
    (DOCS_DIR / "variables.md").write_text("\n".join(lines) + "\n")
    if verbose:
        print(f"  wrote {DOCS_DIR/'variables.md'} ({len(records)} rows)")


def _main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="scripts.audit", description=__doc__)
    p.add_argument("--quiet", "-q", action="store_true")
    a = p.parse_args(argv)
    write_audit(verbose=not a.quiet)
    return 0


if __name__ == "__main__":
    sys.exit(_main())
